M3-108 픽셀 주소 삽입 로직 구현
SWM-M3PRO/GroundFlip-BE pull request #17
Opened 2024-07-05 11:20 UTC by tkdals802

## 작업 내용*
- 네이버 reverse geocoding api에서 좌표를 넣으면 주소를 json으로 받아오기
- 받아온 json을 dto로 직렬화해서 list로 만들기
- pixel의 주소가 null이면 만든 naverAPI를 호출해서 주소를 update하기

## 고민한 내용*

- 스프링에서의 json 직렬화
- 주소를 체크하고 update하기

## 리뷰 요구사항

- 코드 구조, 충돌이 우려되는 부분 

## 스크린샷

2024-07-05 12:03 UTC, koomin1227 requested changes

2024-07-05 12:03 UTC, koomin1227 commented on src/main/java/com/m3pro/groundflip/service/PixelService.java
> +
updateAddress 같은 메서드로 한 감싸서 사용하는 것은 어떨까요? 함수 안에서 너무 많은 일을 표현하고 있는 것 같은데..

2024-07-05 14:04 UTC, qjvk2880 approved these changes

2024-07-05 14:04 UTC, qjvk2880 commented on src/main/java/com/m3pro/groundflip/domain/dto/pixel/NaverAPI/NaverAPIResult.java
> +
클래스 이름도 NaverReverseGeoCodingApiResult 어떨까요?? 조금 길긴하지만 의미가 좀 더 명확해 질 것 같아요!

2024-07-05 14:04 UTC, qjvk2880 commented on src/main/java/com/m3pro/groundflip/service/PixelService.java
> +			List<String> naverAPIResult = getNaverAPIResult(targetPixel.getCoordinate().getX(),
해댱 함수 이름도 getAddressByCoordinate()는 어떨까요?

2024-07-06 03:37 UTC, koomin1227 approved these changes

2024-07-06 03:56 UTC, merged