M3-172 aws S3 이미지 업로드
SWM-M3PRO/GroundFlip-BE pull request #33
Opened 2024-07-16 07:31 UTC by tkdals802

## 작업 내용*

- aws S3 버킷 생성, 접근 권한 부여된 iam 사용자 생성
- multipartfile로 이미지 s3에 업로드
- 업로드시 UUID로 파일 이름 생성
- 이미지 용량 제한 10MB

- 버킷명 : ground-flip-s3
- 이미지 저장 경로 : ground-flip-s3/static

## 고민한 내용*

- @requestbody로 multipartfile을 그대로 받아오면 에러가 났다.
- @RequestPart로 받아와야 에러가 나지 않았다.
- s3이미지 url로 이미지를 읽을 수 있게 권한 설정
- multipartfile에 대한 이해

## 리뷰 요구사항

- 함수, 변수 이름, 로직

## 스크린샷

2024-07-16 07:59 UTC, qjvk2880 approved these changes

2024-07-16 07:59 UTC, qjvk2880 commented on src/main/java/com/m3pro/groundflip/domain/dto/user/UserInfoRequest.java
>  	@Schema(description = "사용자 프로필 사진 주소", example = "http://www.test.com")
설명이 코드와 상이한 부분이 있네요~

2024-07-16 08:59 UTC, koomin1227 requested changes

2024-07-16 08:59 UTC, koomin1227 commented on src/main/java/com/m3pro/groundflip/service/UserService.java
> +			fileS3Url = null;
500 에러를 보내는 것이 좋지 않을까 싶네요.

2024-07-16 08:59 UTC, koomin1227 commented on src/main/java/com/m3pro/groundflip/util/S3Uploader.java
> +    private String convertFiletoUUID(String fileName){
file 을 uuid 로 바꾸는 것이 아니라 file name 을 바꾸는 거니까 converFileNameToUuid 가 어떨까요?

2024-07-16 08:59 UTC, koomin1227 commented on src/main/java/com/m3pro/groundflip/util/S3Uploader.java
> +        String originalFilename = convertFiletoUUID(fileName);
originalFileName 은 위에서 getOriginalFileName 으로 가져오는데 여기서 originalFileName는 잘안어울리는 것 같네요

2024-07-16 08:59 UTC, koomin1227 commented on src/main/java/com/m3pro/groundflip/util/S3Uploader.java
> +        assert fileName != null : "fileName must not null";
assert 는 사용하지 않는 것이 좋을 것 같습니다. 위 조건이 참이 아니면 AssertionError 가 발생하는데 이러면 예외를 잡는게 아니라 스프링 서버가 죽어버립니다. 

그리고 애초에 assert 구문은 런타임에서 기본적으로 활성화도 안된다고 하네요

2024-07-17 02:00 UTC, koomin1227 approved these changes

2024-07-17 02:39 UTC, merged