Feature/m3 238 app version api
SWM-M3PRO/GroundFlip-BE pull request #63
Opened 2024-08-10 18:52 UTC by tkdals802

## 작업 내용*

- version api 작성
- 버전을 post, get하는 api 작성

## 고민한 내용*
- 버전을 get 할때는 가장 최신 날짜의 버전을 가져오도록 했다.
- 현재 버전 하나만 저장하도록 할까 했으나, 과거의 버전도 저장해두면 쓸 일이 있지 않을까 해서 날짜랑 버전을 저장하도록 했다

## 리뷰 요구사항
- 변수, 함수, 로직

2024-08-11 05:36 UTC, koomin1227 approved these changes

2024-08-11 05:36 UTC, koomin1227 commented on src/main/java/com/m3pro/groundflip/controller/VersionController.java
> +	}
시큐리티 적용없이 뚫려있는데 아무나 버전 바꾸면 어떻게되나요?

2024-08-11 10:30 UTC, qjvk2880 approved these changes

2024-08-11 14:04 UTC, koomin1227 requested changes
생각해보니 서버가 최신버전 을 주는게 아니라 클라에서 주는 버전을 최신인지 아닌지 검사하는게 좋을 것 같네요.

서버가 최신 버전을 주면 클라에서는 따로 여러 복잡한 로직을 적용못하고 배포 한시점의 로직만 가지고 판단 할 수 밖에 없을 것 같네요

2024-08-13 03:56 UTC, koomin1227 approved these changes

2024-08-13 03:56 UTC, merged